
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 06 16:50:00 CST 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class SimbolosCJS {
  /* terminals */
  public static final int continuar = 58;
  public static final int distinto = 27;
  public static final int mod = 70;
  public static final int imprimir = 42;
  public static final int disminucion = 37;
  public static final int dosPuntos = 67;
  public static final int valDecimal = 3;
  public static final int detener = 30;
  public static final int coma = 66;
  public static final int igual = 26;
  public static final int valEntero = 2;
  public static final int identificador = 9;
  public static final int corchR = 63;
  public static final int dondecada = 48;
  public static final int inicio = 41;
  public static final int corchL = 62;
  public static final int seleccion = 52;
  public static final int menorIgual = 25;
  public static final int si = 50;
  public static final int mientras = 56;
  public static final int defecto = 54;
  public static final int observador = 32;
  public static final int menos = 14;
  public static final int protegido = 12;
  public static final int columna = 45;
  public static final int menor = 23;
  public static final int var = 38;
  public static final int dondetodo = 49;
  public static final int aumento = 36;
  public static final int EOF = 0;
  public static final int llaveR = 64;
  public static final int mas = 13;
  public static final int valCaracter = 4;
  public static final int para = 55;
  public static final int mayorIgual = 24;
  public static final int verdadero = 6;
  public static final int procesar = 46;
  public static final int error = 1;
  public static final int publico = 11;
  public static final int stringcad = 69;
  public static final int asignar = 7;
  public static final int mayor = 22;
  public static final int llaveL = 65;
  public static final int entero = 39;
  public static final int or = 18;
  public static final int datos = 44;
  public static final int valCadena = 5;
  public static final int por = 15;
  public static final int punto = 68;
  public static final int mensaje = 33;
  public static final int funcion = 43;
  public static final int parR = 61;
  public static final int xor = 20;
  public static final int potencia = 17;
  public static final int obtener = 29;
  public static final int puntoComa = 28;
  public static final int falso = 8;
  public static final int caso = 53;
  public static final int hacer = 57;
  public static final int parL = 60;
  public static final int donde = 47;
  public static final int setelemento = 31;
  public static final int privado = 10;
  public static final int documento = 34;
  public static final int and = 19;
  public static final int not = 21;
  public static final int terminar = 59;
  public static final int retornar = 35;
  public static final int div = 16;
  public static final int decimal = 40;
  public static final int sino = 51;
}

