
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 24 21:42:46 CST 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int ancho = 65;
  public static final int finimagen = 48;
  public static final int fincb = 29;
  public static final int fincaja = 41;
  public static final int finspinner = 36;
  public static final int imagen = 4;
  public static final int valDecimal = 60;
  public static final int derecha = 53;
  public static final int identificador = 61;
  public static final int parrafo = 57;
  public static final int alto = 64;
  public static final int panel = 16;
  public static final int grupo = 67;
  public static final int finpanel = 38;
  public static final int alineado = 66;
  public static final int ruta = 24;
  public static final int ccss = 19;
  public static final int fila = 10;
  public static final int tabla = 14;
  public static final int chtml = 25;
  public static final int menos = 8;
  public static final int finchtml = 44;
  public static final int fintabla = 33;
  public static final int menor = 3;
  public static final int ct = 12;
  public static final int EOF = 0;
  public static final int mas = 7;
  public static final int fincajatexto = 51;
  public static final int error = 1;
  public static final int stringcad = 59;
  public static final int asignar = 56;
  public static final int saltofin = 46;
  public static final int mayor = 2;
  public static final int fincuerpo = 39;
  public static final int valor = 63;
  public static final int por = 55;
  public static final int cuerpo = 17;
  public static final int spinner = 45;
  public static final int click = 26;
  public static final int cb = 13;
  public static final int id = 58;
  public static final int parR = 6;
  public static final int puntoComa = 62;
  public static final int finopcion = 47;
  public static final int finenlace = 49;
  public static final int opcion = 30;
  public static final int cjs = 18;
  public static final int fintitulo = 40;
  public static final int parL = 5;
  public static final int enlace = 31;
  public static final int fintextoa = 37;
  public static final int finccss = 42;
  public static final int centrado = 54;
  public static final int titulo = 15;
  public static final int finfila = 11;
  public static final int encabezado = 50;
  public static final int fincjs = 43;
  public static final int caja = 20;
  public static final int texto = 21;
  public static final int izquierda = 52;
  public static final int fintexto = 32;
  public static final int textoa = 22;
  public static final int cajatexto = 23;
  public static final int div = 9;
  public static final int finencabezado = 35;
  public static final int finct = 28;
  public static final int boton = 27;
  public static final int finboton = 34;
}

