
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 01 18:06:46 CST 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class SimbolosCSS {
  /* terminals */
  public static final int falsebool = 37;
  public static final int mayuscula = 28;
  public static final int colorselect = 43;
  public static final int truebool = 36;
  public static final int opaque = 20;
  public static final int dosPuntos = 8;
  public static final int negrilla = 26;
  public static final int valDecimal = 45;
  public static final int coma = 7;
  public static final int derecha = 23;
  public static final int identificador = 16;
  public static final int corchR = 13;
  public static final int letra = 18;
  public static final int corchL = 12;
  public static final int autoredimension = 41;
  public static final int alineado = 25;
  public static final int tamtex = 21;
  public static final int tamelemento = 34;
  public static final int justificado = 35;
  public static final int vertical = 39;
  public static final int menos = 5;
  public static final int visible = 24;
  public static final int selecttextcolor = 42;
  public static final int EOF = 0;
  public static final int mas = 4;
  public static final int error = 1;
  public static final int stringcad = 46;
  public static final int asignar = 11;
  public static final int fondoelemento = 40;
  public static final int horizontal = 38;
  public static final int idelemento = 33;
  public static final int por = 9;
  public static final int minuscula = 29;
  public static final int id = 14;
  public static final int parR = 3;
  public static final int puntoComa = 10;
  public static final int grupoe = 17;
  public static final int parL = 2;
  public static final int colortext = 30;
  public static final int centrado = 27;
  public static final int texto = 44;
  public static final int izquierda = 32;
  public static final int formato = 22;
  public static final int borde = 19;
  public static final int div = 6;
  public static final int cursiva = 15;
  public static final int capitalt = 31;
}

